FROM ubuntu:16.10

RUN apt-get update -y                             && \
    apt-get install software-properties-common -y && \
    add-apt-repository ppa:webupd8team/java -y    && \
    apt-get update -y                             && \
  	echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections 	  && \
  	apt-get install oracle-java8-installer -y	  && \
  	apt-get install oracle-java8-set-default	  && \
  	apt-get install vim	-y						  && \
  	rm -rf /var/lib/apt/lists/* 				  && \
  	rm -rf /var/cache/oracle-jdk8-installer

RUN mkdir -p /var/log/tomcat

COPY



EXPOSE 9081 

ENTRYPOINT ["java","-jar","server.port=9081","/home/docker/service/libs/apbc-1.jar"]