FROM centos:centos7.1.1503
MAINTAINER yanghaibo <yhb@zjrcu.com>

ENV TZ "Asia/Shanghai"

RUN yum install -y java-1.8.0-openjdk
RUN mkdir -p /home/eagleboot
RUN chmod -R 664 /home/docker/service/

COPY . /home/eagleboot

EXPOSE 8080

# ENTRYPOINT ["java","-jar","server.port=9081","/home/docker/service/libs/apbc-1.jar"]


