FROM alpine:3.9
MAINTAINER yanghaibo <yhb@zjrcu.com>

# 增加java和maven的环境变量
ENV LANG C.UTF-8
ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
ENV PATH $PATH:$JAVA_HOME/jre/bin:$JAVA_HOME/bin
ENV JAVA_VERSION 8u212
ENV JAVA_ALPINE_VERSION 8.212.04-r0
ENV MAVEN_HOME /usr/share/maven
ENV TZ "Asia/Shanghai"

ARG MAVEN_VERSION=3.6.1
ARG SHA=b4880fb7a3d81edd190a029440cdf17f308621af68475a4fe976296e71ff4a4b546dd6d8a58aaafba334d309cc11e638c52808a4b0e818fc0fd544226d952544
ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries
RUN apk add --no-cache curl tar bash procps openjdk8="$JAVA_ALPINE_VERSION" \
  && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
  && echo "${SHA}  /tmp/apache-maven.tar.gz" | sha512sum -c - \
  && mkdir -p $MAVEN_HOME \
  && tar -xzf /tmp/apache-maven.tar.gz -C $MAVEN_HOME --strip-components=1 \
  && rm -f /tmp/apache-maven.tar.gz \
  && ln -s $MAVEN_HOME/bin/mvn /usr/bin/mvn


RUN mkdir -p /home/eagleboot
RUN chmod -R 664 /home/eagleboot
COPY . /home/eagleboot

RUN mvn clean package -f /home/eagleboot/pom.xml

EXPOSE 8080

# ENTRYPOINT ["java","-jar","/home/docker/service/libs/apbc-1.jar"]


