FROM java:8

MAINTAINER yanghaibo <yhb@zjrcu.com>

ENV TZ "Asia/Shanghai"

RUN mkdir -p /home/eagleboot
RUN chmod -R 664 /home/eagleboot

COPY . /home/eagleboot

EXPOSE 8080

# ENTRYPOINT ["java","-jar","server.port=9081","/home/docker/service/libs/apbc-1.jar"]


